version: '3'

services: 
  app: 
    build: .
    command: yarn dev
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app
    depends_on:
      - "db"
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 5uM843#fO
      MYSQL_ROOT_PASSWORD: 7hGSX*68T
    volumes:
      - db:/var/lib/mysql
    ports: 
      - '3306:3306'
volumes:
  db: